pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'docker.io/ahmedmaher07/ivolve'
        KUBE_NAMESPACE = 'default'
        DEPLOYMENT_YAML = 'deployment.yaml'
    }
    stages {
        // Checkout code from GitHub repositories
        stage('Checkout') {
            steps {
                git url: 'https://github.com/IbrahimAdell/Lab.git', branch: 'main'
                dir('jenkins/lab1') {
                    git url: 'https://github.com/wolf8534/ivolve-.git', branch: 'main'
                }
            }
        }

        // Build Docker image from Dockerfile
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t docker.io/ahmedmaher07/ivolve .'  
                }
            }
        }

        // Push Docker image to Docker Hub
        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'Docker_hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh 'docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}'  
                        sh 'docker push ${DOCKER_IMAGE}'  
                    }
                }
            }
        }

        // Edit Deployment.yaml
        stage('Edit Deployment.yaml') {
            steps {
                script {
                    // Use sed to replace the image name in the deployment.yaml file
                    sh "sed -i 's|image:.*|image: $DOCKER_IMAGE|g' $DEPLOYMENT_YAML"
                }
            }
        }

        // Deploy to Kubernetes
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    // Using Secret text, write it to a temporary kubeconfig file
                    withCredentials([string(credentialsId: 'k8s_login', variable: 'K8S_CONFIG')]) {
                        writeFile file: 'kubeconfig', text: "${K8S_CONFIG}"
                        sh "kubectl --kubeconfig=kubeconfig apply -f $DEPLOYMENT_YAML"
                    }
                }
            }
        }

        // Post action (e.g., notifications, additional tasks)
        stage('Post Action') {
            steps {
                script {
                    echo "Deployment to Kubernetes completed successfully!"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
